### ISSUE TITLE
Trouble getting credentials

### ISSUE THREAD

**Issue by JuaniV2002** [ljnath/cPanelBackupPlus#1]
Hi @ljnath!

I'm having some trouble gathering all the credentials needed to set up the script, here are my problems:

- First of all, I'm planning to upload my backups only to a GDrive folder, can I delete the part of the script related to S3?
- Where am I supposed to get the cPanel API token? Looked everywhere but could not find the option to create one.
- About the `GOOGLE_CREDENTIALS_FILE` do you have clear instructions on how to generate that file on the google cloud console? Also, what is the expected value for that variable, a name or the file contents?
- What's the time unit for the `BACKUP_CHECK_DELAY`?
- How do I get all the requirements for the script to run?

Thank you in advance!

**Comment by ljnath** [comment]
1. If you are planning to use only GDrive, you can start the script using -t/--target gdrive. You do not actually remove the s3 codes from the script.
2. You will get the cPanel API token from your cPanel under `Manage API Tokens` (refer screenshot)
3.  You may follow this documentation from Google https://developers.google.com/workspace/guides/create-credentials#service-account .
Create a `Service Account` credentials, eventually you will be able to download a JSON file and refer the same in the env file.
4. The unit is in seconds, I will update the repo with the unit
5. The requirements are listed in the `requirements.txt` file.

I have written a medium article on this https://medium.com/@ljnath/automating-your-cpanel-backups-a-seamless-solution-with-python-and-amazon-s3-using-cpaneltos3-81ca973cd580

![image](https://github.com/user-attachments/assets/7b2f3d18-2630-4944-9505-58a3a2ea5858)

**Comment by JuaniV2002** [comment]
Ok, great! Couple more things:

1. I got the JSON file with all the credentials, how do I refer it inside the `.env` file? Like this: `GOOGLE_CREDENTIALS_FILE={<JSON contents>}`?
2. What's an OK value for `BACKUP_CHECK_DELAY`, half an hour, an hour?
3. I noticed the `requirements.txt` file, my question was how do I get those requirements.

Thank you for your patience!

**Comment by ljnath** [comment]
@JuaniV2002 ,   
1. Place the JSON file in the same location as the `.env` file, and assign the JSON file's name to the `GOOGLE_CREDENTIALS_FILE` variable.
2. Yes, you can try setting it to half an hour; I use that value myself. However, server speed may affect the outcome.
3. Install the required libraries by running `pip install -r requirements.txt`.

**Comment by JuaniV2002** [comment]
Thank you @ljnath! I'll try that as soon as posible.

Issue closed
